### ISSUE TITLE
latest version of kodi results in "Error something went wrong"

### ISSUE THREAD

**Issue by ryanafleming** [ClumsyXBMC/EEVBlog-Xbmc-Plugin#13]
Currently I am running:
- QNAP TS-251
- Firmware version: 4.2.0
- HybridDesk version 3.1.2
- Plugin version: 0.2.7

I am unsure if any of these versions are relevant. I can say that previsouly before updating my qnap firmware/hybrid desk and kodi that the EEVBlog did work on my NAS.

Is there anyway I could assist further or get some sort of log to the reason it may not work?

The application appears to work until after I get the episode listing and click on any individual episode.

**Comment by mintsoft** [comment]
I've got this issue too. The only useful error I've found in the `kodi.log` is:

```
17:18:04 T:2608929600 WARNING: Attempt to use invalid handle -1
```
However I've been adding logging allover the place and tracked it down to:
https://github.com/ClumsyXBMC/EEVBlog-Xbmc-Plugin/blob/master/default.py#L64

**Comment by mintsoft** [comment]
Aha, according to: http://stackoverflow.com/questions/34513784/urlopen-error-errno-1-ssl-c510-error14077417ssl/34514273

It's actually that urllib2 doesn't support SNI; so it can't handshake correctly (hardly a problem that one would expect to encounter in 2016, but hey! This is python we're dealing with here ¬_¬). 

A quick hack is to force all eevblog urls to http and bypass the https requirement until it's either enforced by Dave or SNI support is added

**Comment by mintsoft** [comment]
@ryanafleming https://github.com/ClumsyXBMC/EEVBlog-Xbmc-Plugin/pull/14 has made the plugin work again for me

**Comment by ClumsyXBMC** [comment]
Meh ... thanks for looking into this guys. I really hate the workaround, but I guess it's the best solution for the time being.
